name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'

version-resolver:
  minor:
    labels:
      - "minor"
  default: patch

template: |
  ## What's Changed

  $CHANGES
