[package]
name = "bevy_stdb"
version = "0.7.1"
edition = "2024"
rust-version = "1.93"
description = "A Bevy-native integration for SpacetimeDB with table messages, subscriptions, and reconnect support."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/onx2/bevy_stdb"
homepage = "https://github.com/onx2/bevy_stdb"
documentation = "https://docs.rs/bevy_stdb"
keywords = ["bevy", "spacetimedb", "spacetime", "database", "multiplayer", "ecs"]
categories = ["game-development", "network-programming", "database"]
exclude = [
    ".github/",
]

[dependencies]
bevy_app = "0.18"
bevy_ecs = "0.18"
bevy_state = "0.18"
bevy_time = "0.18"
crossbeam-channel = "0.5"

serde = { version = "1.0", optional = true, features = ["derive"] }
url = { version = "2.5", optional = true }
base64 = { version = "0.22", optional = true }
sha2 = { version = "0.11", optional = true }

[features]
default = []

auth = [
    "dep:url",
    "dep:base64",
    "dep:serde",
    "dep:keyring",
    "dep:webbrowser",
    "dep:web-sys",
]

# Native target crates
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
spacetimedb-sdk = "2.1"
keyring = { version = "3.6", optional = true }
webbrowser = { version = "1", optional = true }

# Browser target crates
[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
spacetimedb-sdk = { version = "2.1", feature = ["browser"] }
js-sys = { version = "0.3", default-features = false, features = ["futures"] }
web-sys = { version = "0.3", default-features = false, optional = true, features = [
    "Window",
    "Crypto"
] }

# reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
# url = "2.5"
# webbrowser = "1"
# web-sys = { version = "0.3", optional = true, features = ["Window", "Storage", "History", "Location", "Crypto"] }
# js-sys = { version = "0.3", optional = true }
# base64 = "0.22"
# sha2 = "0.10"
# futures-lite = "2"
# dirs = "6"
# web-sys = { version = "0.3", optional = true, default-features = false, features = ["futures"] }
# serde = { version = "1.0", features = ["derive"], optional = true }
# oauth2 = { version = "0.5", optional = true }
# keyring = { version =  "3.6", optional = true }
# https://crates.io/crates/ureq/3.3.0
# reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
# url = "2.5"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
