//! What a generated table accessor must provide to be bound, stated once.
//!
//! The SDK spreads a table across a generic associated type and four traits, so saying "this
//! accessor's handle reports inserts of its row type" takes a higher-ranked bound several lines
//! long. These traits say it in one place each; everything else names the trait.
use super::policy::carries_event;
use crate::{
    channel_bridge::{channel_sender, register_channel},
    message::{RowEvent, SharedRowEvent, TableChange},
};
use bevy_app::App;
use bevy_ecs::prelude::World;
use spacetimedb_sdk::__codegen::{
    DbContext, InModule, SpacetimeModule, TableAccessor, TableLike, WithDelete, WithInsert,
    WithUpdate,
};
use std::any::TypeId;

/// The event context the SDK hands the row callbacks of `TRow`'s module.
type RowEventContext<TRow> = <<TRow as InModule>::Module as SpacetimeModule>::EventContext;

mod sealed {
    pub trait Sealed<C> {}
}

/// A `spacetime generate` table accessor whose row changes can be forwarded into Bevy.
///
/// Implemented for every generated accessor; there is nothing to implement by hand.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is not a table accessor for this connection",
    note = "pass a `...TableAccessor` type generated by `spacetime generate` for the same module as the plugin"
)]
pub trait TableSource<C: DbContext>: sealed::Sealed<C> + 'static {
    /// The row type, which keys the channel every accessor over it shares.
    #[doc(hidden)]
    fn row_type() -> TypeId;

    /// Registers the [`TableChange`] channel for the row type.
    #[doc(hidden)]
    fn register_channel(app: &mut App);
}

/// A [`TableSource`] that reports inserted rows. Every table, view, and event table does.
#[diagnostic::on_unimplemented(message = "`{Self}` does not report inserted rows")]
pub trait OnInsert<C: DbContext>: TableSource<C> {
    /// Forwards `on_insert` into the row type's channel.
    #[doc(hidden)]
    fn bind_insert(world: &World, db: &C::DbView);
}

/// A [`TableSource`] that reports deleted rows. Tables and views do; event tables do not.
#[diagnostic::on_unimplemented(
    message = "`{Self}` does not report deleted rows",
    note = "an event table only reports inserts: register it with `add_event_table`"
)]
pub trait OnDelete<C: DbContext>: TableSource<C> {
    /// Forwards `on_delete` into the row type's channel.
    #[doc(hidden)]
    fn bind_delete(world: &World, db: &C::DbView);
}

/// A [`TableSource`] that reports updated rows, which takes a primary key to pair old with new.
#[diagnostic::on_unimplemented(
    message = "`{Self}` does not report updated rows",
    note = "only a table with a primary key does: register this one with `add_table_without_pk`, `add_view`, or `add_event_table`"
)]
pub trait OnUpdate<C: DbContext>: TableSource<C> {
    /// Forwards `on_update` into the row type's channel.
    #[doc(hidden)]
    fn bind_update(world: &World, db: &C::DbView);
}

impl<C, T> sealed::Sealed<C> for T
where
    C: DbContext,
    T: TableAccessor<C::DbView>,
{
}

impl<C, T> TableSource<C> for T
where
    C: DbContext,
    T: TableAccessor<C::DbView> + 'static,
    T::Row: Send + Sync + InModule + 'static,
    RowEvent<T::Row>: Send + Sync,
{
    fn row_type() -> TypeId {
        TypeId::of::<T::Row>()
    }

    fn register_channel(app: &mut App) {
        register_channel::<TableChange<T::Row>>(app);
    }
}

impl<C, T> OnInsert<C> for T
where
    C: DbContext,
    T: TableSource<C> + TableAccessor<C::DbView>,
    T::Row: Send + Sync + Clone + InModule + 'static,
    RowEvent<T::Row>: Send + Sync + Clone,
    for<'db> T::Handle<'db>:
        TableLike<Row = T::Row, EventContext = RowEventContext<T::Row>> + WithInsert,
{
    fn bind_insert(world: &World, db: &C::DbView) {
        let sender = channel_sender::<TableChange<T::Row>>(world);
        let with_event = carries_event::<T::Row>(world);
        T::get(db).on_insert(move |ctx, row| {
            let _ = sender.send(TableChange::Insert {
                event: with_event
                    .then(|| SharedRowEvent::<T::Row>::new(event_of::<T::Row>(ctx).clone())),
                row: row.clone(),
            });
        });
    }
}

impl<C, T> OnDelete<C> for T
where
    C: DbContext,
    T: TableSource<C> + TableAccessor<C::DbView>,
    T::Row: Send + Sync + Clone + InModule + 'static,
    RowEvent<T::Row>: Send + Sync + Clone,
    for<'db> T::Handle<'db>:
        TableLike<Row = T::Row, EventContext = RowEventContext<T::Row>> + WithDelete,
{
    fn bind_delete(world: &World, db: &C::DbView) {
        let sender = channel_sender::<TableChange<T::Row>>(world);
        let with_event = carries_event::<T::Row>(world);
        T::get(db).on_delete(move |ctx, row| {
            let _ = sender.send(TableChange::Delete {
                event: with_event
                    .then(|| SharedRowEvent::<T::Row>::new(event_of::<T::Row>(ctx).clone())),
                row: row.clone(),
            });
        });
    }
}

impl<C, T> OnUpdate<C> for T
where
    C: DbContext,
    T: TableSource<C> + TableAccessor<C::DbView>,
    T::Row: Send + Sync + Clone + InModule + 'static,
    RowEvent<T::Row>: Send + Sync + Clone,
    for<'db> T::Handle<'db>:
        TableLike<Row = T::Row, EventContext = RowEventContext<T::Row>> + WithUpdate,
{
    fn bind_update(world: &World, db: &C::DbView) {
        let sender = channel_sender::<TableChange<T::Row>>(world);
        let with_event = carries_event::<T::Row>(world);
        T::get(db).on_update(move |ctx, old, new| {
            let _ = sender.send(TableChange::Update {
                event: with_event
                    .then(|| SharedRowEvent::<T::Row>::new(event_of::<T::Row>(ctx).clone())),
                old: old.clone(),
                new: new.clone(),
            });
        });
    }
}

/// The event a row callback's context carries.
fn event_of<TRow: InModule>(ctx: &RowEventContext<TRow>) -> &RowEvent<TRow> {
    use spacetimedb_sdk::__codegen::AbstractEventContext;
    ctx.event()
}
